name: CICD

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_SITE_PROJECT_ID }}

on:
  push:
    branches:
      - main

jobs:
  run:
    name: Run
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 8.5.1
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install global
        run: pnpm add -g vercel
      - name: Install workspace
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Pull Vercel Environment Information
        run: cd apps/site && vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: cd apps/site && vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
